# Generated by Django 6.0.7 on 2026-07-30 03:55

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    GROUPS = ['Administrator', 'Faculty', 'Guardian', 'Student', 'IT']

    for group_name in GROUPS:
        Group.objects.get_or_create(name=group_name)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    GROUPS = ['Administrator', 'Faculty', 'Guardian', 'Student', 'IT']

    Group.objects.filter(name__in=GROUPS).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=remove_groups),
    ]
