# Generated by Django 6.0.7 on 2026-08-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='user.userinvitation'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='group_role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Faculty', 'Faculty'), ('Student', 'Student')], max_length=13),
        ),
    ]
